### ISSUE TITLE
Arrange the issue labels

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#1]
* Review the default labels.
* Add necessary new labels.

**Comment by SouthAscend** [comment]
I've added the necessary labels.

**Comment by SouthAscend** [comment]
## Description
The issue description.

## Tasks
- [x] ~Review the default labels.~
- [x] ~Add necessary new labels.~

## Deadline
19/02/2024 - 23.59

## Reviewer
No reviewer
