### ISSUE TITLE
Class diagram

### ISSUE THREAD

**Issue by SouthAscend** [bounswe/bounswe2024group5#106]
## Description
We need a class diagram for our project

## Tasks
- [ ] Create Class Diagrams

## Estimated Time
120

## Deadline
07/04/2024 - 23.59

## Reviewer
@set120120  - 08/04/2024 23.59

**Comment by semihYILMAZ37** [comment]
The first draft of the [class diagram](https://github.com/bounswe/bounswe2024group5/wiki/UML-Diagram-%E2%80%90-Class-Diagram) has been done by @odenizddd , @SouthAscend and I. We faced some unclear points in the requirements. In the next meeting we will discuss those aspects and revise the diagram.

**Comment by set120120** [comment]
I would like to give a little feedback for the first draft. Do you think it would make sense to keep a list of disliked or blocked posts in RegisteredUser class?

**Comment by SouthAscend** [comment]
Compared to the fields in 'Profile', we thought that 'likedPosts' and 'blockedUsers' were more private information. That's why we put them in "RegisteredUser." However, we can modify it as needed.

**Comment by semihYILMAZ37** [comment]
I revised the diagram according to TA's feedback. The new diagram can be seen [here](https://github.com/bounswe/bounswe2024group5/wiki/Class-Diagram-v2).
@odenizddd @SouthAscend I am open to your feedback on this.

Changes are:
* corrected the direction of compositions
* removed feed
* added set functions (some of them are add/delete type for list fields)
* search history has been moved to profile class
* search engine modified.
* guestUser class deleted. Usercontroller class added for registration and login.

**Comment by SouthAscend** [comment]
@semihYILMAZ37 Did we remove the feed feature completely or is it just for the class diagram? If the feture remained, why are we removing it from the diagram? Same goes for the guestUser class too. Other than that it seems better with your improvements.

**Comment by set120120** [comment]
@odenizddd @semihYILMAZ37 @SouthAscend I think [this version](https://github.com/bounswe/bounswe2024group5/wiki/Class-Diagram-v2) looks very nice. It meets all the requirements of feedback.

**Comment by semihYILMAZ37** [comment]
> @semihYILMAZ37 Did we remove the feed feature completely or is it just for the class diagram? If the feture remained, why are we removing it from the diagram? Same goes for the guestUser class too. Other than that it seems better with your improvements.

Feed does not have anything to be stored hence it does not need to have a class. It is just a process. In new diagram, search engine class has a method to return feed for a user. I think returning the feed has similarities with returning search results. Therefore I added feed method to search engine class.

About guest user class, we dont need to store any information of guest user. Then there is no reason to make it a class.

**Comment by semihYILMAZ37** [comment]
@set120120 this issue is ready to review.

**Comment by set120120** [comment]
Everything seems okay. Good job @semihYILMAZ37 @odenizddd @SouthAscend
