### ISSUE TITLE
Fix the Requirements according to feedback

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#107]
## Description
We received feedback from the TA on discord (on April 7th) about the software requirements. We need to fix some parts.
Currently, the `Interactions` section seems redundant since it belongs to the `User` section.

## Tasks
- [x]  Move the interactions as a subsection to Users.
- [x] Get rid of the contradictory requirements in the `user-to-system` section.

## Estimated Time
15 mins

## Deadline
Date(10/04/2024) - 23.59

## Reviewer
@ramazanoacar  - Deadline of the review(14/04/2024 - 23.59)

**Comment by ramazanoacar** [comment]
@ebrarkiziloglu from page history it could be seen that the necessities of the task are accomplished. It looks fine. Thanks for your effort!
