### ISSUE TITLE
Vote on the Platform Name

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#108]
## Description
We collected our ideas for the platform in a [discussion form](https://github.com/bounswe/bounswe2024group5/discussions/102). Now, let's vote for the best name!

## Estimated Time
5 mins.

## Deadline
Date(15/04/2024) - 23.58

## Reviewer
Reviewer not needed.

**Comment by semihYILMAZ37** [comment]
melodify has been selected as the name of our platform with 7 votes.
