### ISSUE TITLE
Load Feed Page sequence diagram - @ebrarkiziloglu

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#112]
## Tasks
- [x] Create Load Feed Page sequence diagram

## Estimated Time
20 mins.

## Deadline
Date(28/04/2024) - 23.59

## Reviewer
@set120120  - Deadline of the review(29/04/2024 - 23.59)

**Comment by ebrarkiziloglu** [comment]
[Load page diagram](https://github.com/bounswe/bounswe2024group5/wiki/Sequence-Diagrams#8-load-feed-page) is available.

**Comment by set120120** [comment]
It seems okay.
