### ISSUE TITLE
⁠Interact with post sequence diagram - @ebrarkiziloglu

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#113]
## Tasks
- [x] Create ⁠Interact with post sequence diagram

## Estimated Time
20 mins.

## Deadline
Date(28/04/2024) - 23.59

## Reviewer
@semihYILMAZ37  - Deadline of the review(29/04/2024 - 23.59)

**Comment by ebrarkiziloglu** [comment]
I added [liked a post](https://github.com/bounswe/bounswe2024group5/wiki/Sequence-Diagrams#9-like-a-post) and [comment to a post](https://github.com/bounswe/bounswe2024group5/wiki/Sequence-Diagrams#10-comment-to-a-post) diagrams. This issue is ready for review.

**Comment by semihYILMAZ37** [comment]
It seems like that the diagrams display what happens at the client side but they represent server side poorly. At serverside there is no class called Feed Page. There must be something in between feed page and the database.

For like a post case, "addLikedUser(user: User)" method of coresponding post object should be used.
For comment to a post case, a comment object must be initialized by its constructor method. Then the newly created object must be passed by "addComment(comment: Comment)" method to the post object which is commented to.

**Comment by ebrarkiziloglu** [comment]
That's a great feedback Semih thank you. I reviewed the class diagram and adjusted my diagrams accordingly. Can you review @semihYILMAZ37 ?
