### ISSUE TITLE
⁠Login sequence diagram - @ramazanoacar

### ISSUE THREAD

**Issue by ramazanoacar** [bounswe/bounswe2024group5#117]

**Comment by ramazanoacar** [comment]
I tried to add the sequence diagram for login and register but I am not sure if I get the idea of sequence diagram. Can you review the diagrams please? @odenizddd @set120120

**Comment by odenizddd** [comment]
I believe it is customary to use the words 'success' and 'failure' to denote return status. So perhaps you can change that.
Other than that I myself am a little bit confused with which actor should be placed between the user and the database. However I imagine the middle actor should be one of the classes from our UML class diagram.

**Comment by set120120** [comment]
It may be more logical to return success / failure instead of 0 or 1 here. If it fails, it would also be good to point out why it failed. For example, if the registration fails, it would be good to specify whether it fails because "there is such a user" or whether it fails because there is a systemic error.

**Comment by ramazanoacar** [comment]
I couldn't find what I can add from UML class diagrams. Maybe one of the user, guest user or registered user? what do you think? I believe there should be an another class for login() or register() functions in the class diagram If i'm not looking from the wrong perspective @set120120 @odenizddd

**Comment by ramazanoacar** [comment]
now I looked aat the class diagram v2, I think it should be user controller. I made the changes. could you review again please? @set120120 @odenizddd

**Comment by odenizddd** [comment]
Yes, you are right. UserController class is the way to go in my opinion as well. We can close the issue if @set120120 agrees too.
