### ISSUE TITLE
Create See Search History Sequence Diagram

### ISSUE THREAD

**Issue by arincdemir** [bounswe/bounswe2024group5#120]
## Description
Create the sequence diagram for the user seeing their search history

## Tasks
- [X] Learn about sequence diagrams
- [X] Put the sequence diagram to wiki

## Estimated Time
50 min

## Deadline
Date(23/04/2024) - 23:59

## Reviewer
@odenizddd

**Comment by arincdemir** [comment]
I just added the sequence diagram but I need someone to take a look. [link](https://github.com/bounswe/bounswe2024group5/wiki/Sequence-Diagrams#11-see-search-history).
@odenizddd can you take a look?

**Comment by odenizddd** [comment]
It look ok fro the most part. However I'm not sure if 'API' is an acceptable component in a sequence diagram. Shouldn't it be a class from our UML diagram? What do you think @ebrarkiziloglu ?

**Comment by arincdemir** [comment]
I changed API to SearchEngine, where the search history resides. However, I couldn't see a method of the class which retrieves the search history. Do you guys think thats a problem?

**Comment by odenizddd** [comment]
It might be the case that our UML diagram is imcomplete. We might revisit our class structures in the future but for now your sequence diagram look good. Thank you. Closing the issue.

**Comment by arincdemir** [comment]
@odenizddd I happened to be used the first version of the class diagram. There is the function necessary in the second version. I think that the UML diagram might be fine. I will fix my sequence diagram now accordint to the version 2
