### ISSUE TITLE
Design API

### ISSUE THREAD

**Issue by semihYILMAZ37** [bounswe/bounswe2024group5#122]
### Issue Description

Design API paths, request objects and response objects and document them.

### Tasks

- [x] Design paths.
- [x] Design request bodies and response objects.
- [x] Document the API

### Estimated Time

240

### Deadline

25/04/2024

### Reviewer

@set120120 - deadline (26/04/2024)

**Comment by semihYILMAZ37** [comment]
first draft of [API Path Design](https://github.com/bounswe/bounswe2024group5/wiki/API-Path-Design) is available.

**Comment by set120120** [comment]
I have one question two you. In the design, you wrote "PUT /users/{userId}/profile" and "DELETE /users/{userId}/profile". These queries mean creating and deleting an account? Others are okay. Good job for both of you @HutkuC @semihYILMAZ37

**Comment by odenizddd** [comment]
API desing looks good. I think we can go forward with it.

**Comment by semihYILMAZ37** [comment]
> I have one question to you. In the design, you wrote "PUT /users/{userId}/profile" and "DELETE /users/{userId}/profile". These queries mean creating and deleting an account? Others are okay. Good job for both of you

Those queries are used to manipulate "the profile" attached to user rather than user itself. POST request is for creating a new profile while PUT query is to update profile details. And DELETE is to delete it. I am not sure whether they will be needed but I think it is good practice to provide them as API.

**Comment by set120120** [comment]
Thank you for effort. Good job teammates. @HutkuC @semihYILMAZ37
