### ISSUE TITLE
Draw Create Post Sequence Diagram

### ISSUE THREAD

**Issue by odenizddd** [bounswe/bounswe2024group5#131]
## Description
Draw sequence diagram for creating a post.

## Reviewer
@Ultiminati

**Comment by odenizddd** [comment]
I added the sequence diagram for creating a post in out [sequence diagrams page](https://github.com/bounswe/bounswe2024group5/wiki/Sequence-Diagrams).

**Comment by Ultiminati** [comment]
Adequately done, closing the issue.
