### ISSUE TITLE
Design Database

### ISSUE THREAD

**Issue by semihYILMAZ37** [bounswe/bounswe2024group5#132]
## Description
Design a relational database for the application.

## Tasks
- [x] Design the database
- [x] Provide sql queries to create tables

## Estimated Time
180

## Deadline
Date(29/04/2024) - 23:59

## Reviewer
@set120120 (30/04/2024 - 23:59)

**Comment by set120120** [comment]
I think tables seem okay for now. Good job @semihYILMAZ37
