### ISSUE TITLE
Create appropriate labels for implementation

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#137]
## Description
We need to add implementation specific issue labels, such as mobile, back-end, etc. 

## Estimated Time
15 mins.

## Deadline
Date(28/04/2024) - 23.59

## Reviewer
@SouthAscend - Deadline of the review(30/04/2024 - 23.59)

**Comment by ebrarkiziloglu** [comment]
The necessary labels I came up with are the following:
`api, wikidata, database, front-end, back-end, mobile`.

We might need more. @SouthAscend do you have any other ideas for implementation related issue labels?

**Comment by SouthAscend** [comment]
@ebrarkiziloglu I think they would be better with a prefix similar to `type:`, `status:`, `priority:`. So I added the `team:` prefix. If you disagree with it, we can remove it again. Other than that, additional labels are well thought out. Sorry for the delay on my behalf. You can close the issue after deciding if the prefixes are necessary or not. I've also added descriptions to them.

**Comment by ebrarkiziloglu** [comment]
@SouthAscend thank you for the review and great contribution Guney. I think they are more organized now.
