### ISSUE TITLE
Revision for RAM

### ISSUE THREAD

**Issue by set120120** [bounswe/bounswe2024group5#138]
## Description
The RAM needs to be updated/revised according to some feedback.
## Tasks
- [x] Add necessary rows to RAM.
- [x] Remove unnecessary rows from RAM.

## Estimated Time
60 min

## Deadline
28.04.2024 (23.59)

## Reviewer
@ebrarkiziloglu

**Comment by set120120** [comment]
I've changed order of rows in RAM. From now on, the meeting section will be at the top of RAM. Then, there is the tasks section. I removed places that should not be in RAM and added new lines to RAM according to the latest issues. So, you can review now. @ebrarkiziloglu

**Comment by ebrarkiziloglu** [comment]
WOW, it looks much more compact now with meetings at the top and tasks following them.

Just a couple nits:
- Adding weekly contributions can be completely removed, as it is a recurring task and does not hold much technical value on its own.
- Some very closely related tasks (that are not technical but mostly for documentation purposes) COULD be written in one row to increase readability. Such as:
   - Discuss and suggest issue labels & Create issue labels
   - Find appropriate question about requirements & Gather requirement questions
   - Create the mock-ups & Create wiki page for mock-ups
   
We now have a shorter and more readable RAM. Thanks for the great work Suleyman!

**Comment by set120120** [comment]
You are absolutely right. I adjusted the RAM according to the feedback you gave.

**Comment by ebrarkiziloglu** [comment]
LGTM! 💯
