### ISSUE TITLE
⁠Refresh page sequence diagram - @Ultiminati

### ISSUE THREAD

**Issue by Ultiminati** [bounswe/bounswe2024group5#143]
## Tasks
- [x] Create refresh page sequence diagram

## Estimated Time
30

## Deadline
Date(29/04/2024) - 10.00

## Reviewer
@odenizddd - Deadline of the review(29/04/2024 - 23.00)

**Comment by Ultiminati** [comment]
Had to open another one as I could not mention the main issue.

**Comment by Ultiminati** [comment]
Done, waiting for your review @odenizddd

**Comment by Ultiminati** [comment]
That lasted like at least 90 mins, a bad estimate in my part :D

**Comment by odenizddd** [comment]
Very detailed work. I'm sure you've learned ins and outs of mark up language used for sequence diagrams very well.
Good work. Closing the issue.
