### ISSUE TITLE
Dockerize Front End

### ISSUE THREAD

**Issue by odenizddd** [bounswe/bounswe2024group5#145]
## Description
Dockerize front end application and make sure it works with the backend.

## Tasks
- [x] Create dockerfile
- [x] Integrate using docker compose.

## Estimated Time
1 hour

## Deadline
Date(30/04/2024) - 11.00 AM

## @HutkuC 
@Reviewer - Deadline of the review(30/04/2024 - hour)

**Comment by odenizddd** [comment]
I pushed the dockerized front end code in [this](https://github.com/bounswe/bounswe2024group5/tree/frontend) branch. Can you please verify that it works seamlessly wtih the rest of the containers @HutkuC . I was able to issue 'dockore-comppose up' and serve the page from within the container.

**Comment by HutkuC** [comment]
Everything works fine, well done 👍
