### ISSUE TITLE
Create Back-End Meeting Notes

### ISSUE THREAD

**Issue by set120120** [bounswe/bounswe2024group5#162]
## Description
We need to convert meeting notes to a wiki page.
## Tasks
- [x] Initiate wiki page.
- [x] Write notes in the page.

## Estimated Time
50 mins
## Deadline
30.04.2024 - 23.59

## Reviewer
@semihYILMAZ37  - Deadline of the review(dd/mm/yyyy - hour)

**Comment by set120120** [comment]
I wrote our meeting notes to [here](https://github.com/bounswe/bounswe2024group5/wiki/Back%E2%80%90End-Meeting-Notes). Could you please check them and give feedback? @semihYILMAZ37

**Comment by semihYILMAZ37** [comment]
The notes are very good. I changed some parts a little and added coresponding issues. Thanks for great work!
