### ISSUE TITLE
Design and implement a post component

### ISSUE THREAD

**Issue by Ultiminati** [bounswe/bounswe2024group5#172]
## Tasks
- [x] #178
- [x] #179
- [x] #180
- [x] #181
- [ ] #182
- [ ] #183
- [x] #184

## Estimated Time
200

## Deadline
Date(13/05/2024) - 23.00

## Reviewer
@ebrarkiziloglu  - Deadline of the review(15/05/2024 - 10.00)

**Comment by odenizddd** [comment]
Our implementation wasn't perfect but that is all we can do for this milestone. Should we close this issue @Ultiminati

**Comment by ebrarkiziloglu** [comment]
Great job Frontend team <3
Closing the issue.
