### ISSUE TITLE
Create the search page

### ISSUE THREAD

**Issue by Ultiminati** [bounswe/bounswe2024group5#173]
## Description
We divided the tasks into time frames in our meeting. Here, they are together.

## Tasks
- [ ] #185
- [x] #186
- [x] #187
- [ ] #188

## Estimated Time
200

## Deadline
Date(16/05/2024) - 23.00

## Reviewer
@ramazanoacar - Deadline of the review(17/05/2024 - 10.00)

**Comment by odenizddd** [comment]
@Ultiminati @SouthAscend review needed.

**Comment by Ultiminati** [comment]
Nicely done.
