### ISSUE TITLE
Provide file upload in backend

### ISSUE THREAD

**Issue by set120120** [bounswe/bounswe2024group5#209]
## Description
We need to provide users to be able to upload files like images. Therefore, I need to learn how to do this.
## Tasks
- [x] Learn Google Cloud Services and Spring to upload files
- [x] Provide necessary APIs for this task.

## Estimated Time
240 mins

## Deadline
16.05.2024 - 21.59

## Reviewer
@semihYILMAZ37

**Comment by set120120** [comment]
It is ready in [branch](https://github.com/bounswe/bounswe2024group5/tree/file-upload-3).

**Comment by semihYILMAZ37** [comment]
good job
