### ISSUE TITLE
Implement Create Post Dialog

### ISSUE THREAD

**Issue by odenizddd** [bounswe/bounswe2024group5#234]
## Description
We need a component that can be used to create new posts. This component should be implemented like a dialog. When a button is clicked it should open and take text and image input. When the post button is clicked, collected inputs should be sent to backend endpoints. And if any place other than the dialog is clicked, it should close as well.

## Estimated Time
4 hours

## Reviewer
@Reviewer - @ebrarkiziloglu

**Comment by odenizddd** [comment]
I implemented the create post component. Review needed @ebrarkiziloglu

**Comment by ebrarkiziloglu** [comment]
It works splendidly. Great work!
