### ISSUE TITLE
Implement Web Search Functionality

### ISSUE THREAD

**Issue by odenizddd** [bounswe/bounswe2024group5#235]
## Description
Our backend endpoint returns both relevant posts and wikidata links. Users shall be able to see them both. We can use the previously created post component to displat the results. However for wikidata items we need another component. Also we need a way of switching between feed and search results. This can be achieved by tabs.

## Tasks
- [x] Create search bar.
- [x] Implement wikidata component.
- [x] Implement tabs.

## Estimated Time
6 hours

## Reviewer
@HutkuC

**Comment by odenizddd** [comment]
Done. Please review @HutkuC

**Comment by HutkuC** [comment]
Tested and reviewed before the demo session. Closing the issue.
