### ISSUE TITLE
Move your weekly contributions to archive for 352 in your personal pages.

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#248]
## Description
As part of the first lab, we are required to revise our personal Wiki pages. 

## Tasks
- [x] @odenizddd 
- [x] @HutkuC 
- [x] @arincdemir 
- [x] @ramazanoacar 
- [x] @ebrarkiziloglu 
- [x] @semihYILMAZ37 
- [x] @set120120 
- [x] @fahreddinozcan
 
## Estimated Time
20 mins

## Deadline
Date(24/09/2024) - 17.00

## Reviewer
@Reviewer - Deadline of the review(dd/mm/yyyy - hour)

**Comment by fahreddinozcan** [comment]
I will be creating/updating my personal wiki, once the repo access is provided with #256

**Comment by set120120** [comment]
I have organized my personal wiki page according to cmpe451.

**Comment by fahreddinozcan** [comment]
I've organised my personal wiki page.

**Comment by ramazanoacar** [comment]
I've organsied my personal wiki page for cmpe 451.

**Comment by HutkuC** [comment]
Closing the issue because everyone is done.
