### ISSUE TITLE
Revise the Wiki Home page for the new project

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#250]
## Description
As part of the revision for 

## Tasks
- [x] Clear out the old content.
- [x] Add the description for the new project.

## Estimated Time
20 mins

## Deadline
Date(24/09/2024) - 16.00

## Reviewer
@semihYILMAZ37 - Deadline of the review(24/09/2024 - 17.00)

**Comment by ebrarkiziloglu** [comment]
home page is revised.

**Comment by semihYILMAZ37** [comment]
thanks, it looks cool
