### ISSUE TITLE
Create readme file for the new project.

### ISSUE THREAD

**Issue by odenizddd** [bounswe/bounswe2024group5#254]
## Description
Update the old readme file to add new team members (Fahreddin Özcan) and also change the project description.

## Tasks
- [x] Add Fahreddin Özcan as a member.
- [x] Update the project description.

## Estimated Time
15 mins

## Deadline
24/09/2024

## Reviewer
@ebrarkiziloglu

**Comment by ebrarkiziloglu** [comment]
merged the changes to the main branch
