### ISSUE TITLE
Revise Wiki Sidebar Page

### ISSUE THREAD

**Issue by semihYILMAZ37** [bounswe/bounswe2024group5#257]
## Description
A new sidebar for the new course should be prepared. 

## Tasks
- [x] Archieve 352 related pages.
- [x] Add 451 related pages to the sidebar.

## Estimated Time
15 min

## Deadline
Date(24/09/2024) - 17:00

## Reviewer
@set120120  - (24/09/2024 - 19:00)

**Comment by set120120** [comment]
Everything is OK. Sorry for late review.
