### ISSUE TITLE
Issue: Prepare Meeting Notes #1

### ISSUE THREAD

**Issue by fahreddinozcan** [bounswe/bounswe2024group5#260]
### Issue Description

We need the meeting notes of LAB#1, 24.09.2024 to be added to wiki page.

### Tasks

- [x] Meeting Notes #1

### Estimated Time

30

### Deadline

24/09/2024 - 18.00

### Reviewer

@semihYILMAZ37 - Deadline of the review (24/09/2024 -  20.00)

**Comment by fahreddinozcan** [comment]
We can close this, now that lab meeting notes is added to the wikipage [here](https://github.com/bounswe/bounswe2024group5/wiki/Lab-Meeting-%231-%7C-24.09.2024)

**Comment by fahreddinozcan** [comment]
We can close this after your review @semihYILMAZ37

**Comment by semihYILMAZ37** [comment]
thanks for your effort
