### ISSUE TITLE
Update Lab Report

### ISSUE THREAD

**Issue by set120120** [bounswe/bounswe2024group5#261]
## Description
There should be some related links in Lab Report.
## Tasks
- [x] Find all related links and add them to Lab Report wiki page.

## Estimated Time
15 min.

## Deadline
24.09.2024 - 19.59

## Reviewer
@ebrarkiziloglu

**Comment by set120120** [comment]
All is ready and waiting your review @ebrarkiziloglu .

**Comment by ebrarkiziloglu** [comment]
Good work !
