### ISSUE TITLE
Create General Meeting Note

### ISSUE THREAD

**Issue by set120120** [bounswe/bounswe2024group5#262]
## Description

We had a meeting on Friday (27.09.2024), the notes need to be uploaded to the wiki page.

## Tasks
- [x] Convert notes to proper format
- [x] Upload them to wiki

## Estimated Time
50 minutes

## Deadline
27.09.2024 - 23.59

## Reviewer
@fahreddinozcan 
29.09.2024 - 23.59

**Comment by set120120** [comment]
I've uploaded the [general meeting note #1](https://github.com/bounswe/bounswe2024group5/wiki/General-Meeting-%231). You can check and review it. @fahreddinozcan

**Comment by fahreddinozcan** [comment]
Thanks for your efford. Everything seems fine.
