### ISSUE TITLE
Write Requirements of the Project

### ISSUE THREAD

**Issue by set120120** [bounswe/bounswe2024group5#266]
## Description
For last week's questions, requirements need to be written for the concept determined as a result of discussions both with Furkan and within the group.

## Tasks
- [x] #270
- [x] #268
- [x] #279

## Estimated Time
6 hours

## Deadline
08.10.2024 - 12.00

## Reviewer
@odenizddd  - 10.10.2024

**Comment by set120120** [comment]
We have completed all requirements for now. We are waiting for your detailed review @odenizddd .

**Comment by semihYILMAZ37** [comment]
thanks for the review!

* I believe that account recovery by email is not an easy feature. It can be good to remove this requirement.
* For multiple questions at once, we should discuss it at the lab today.
* We removed requirement 1.2.2.4.

**Comment by odenizddd** [comment]
Seeing as we won't be implementing account recovery by email, and muliple question creation, closing this issue now.
