### ISSUE TITLE
Write Lab Report 2

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#267]
## Description
Lab report 2 will be written. 
 
## Estimated Time
20 mins

## Deadline
Date(01/10/2024) - 20.00

## Reviewer
@set120120  - Deadline of the review(01/10/2024 - 20.00)

**Comment by ramazanoacar** [comment]
@ebrarkiziloglu I think there is a problem with the reviewer of the task

**Comment by ebrarkiziloglu** [comment]
> @ebrarkiziloglu I think there is a problem with the reviewer of the task

Right, thank you for pointing that out Ramazan!

@set120120 and @odenizddd reviewed the lab report while communicating on WhatsApp. Closing the issue now.
