### ISSUE TITLE
Write System Requirements

### ISSUE THREAD

**Issue by set120120** [bounswe/bounswe2024group5#268]

**Comment by set120120** [comment]
I have written the first version of the system requirements. If there are things you want to add or change, feel free to do so. We will make our requirements much more suitable as our project progresses. @semihYILMAZ37

**Comment by semihYILMAZ37** [comment]
The system requirements looks cool. Thanks for your effort. 
I added some requirements to 1.2.1 word / quiz requirements. There is something I am confused about. 1.2.1.6 says that
` The system shall keep the difficulty levels, definitions, translations, synonyms, antonyms, words with similar meanings, categories of words.` Our project description says that `  Creation of quizzes will utilize Linked Data, such as Lexvo, to get the words, senses and translations.` So I believe that the system should not keep all the details but utilize linked data sources. It can be good to discuss this requirement in the next meeting.

**Comment by set120120** [comment]
Thank you for adjustments. We'll review all requirements together later. For now, I am closing this issue.
