### ISSUE TITLE
Issue: Create Lab Meeting Notes #2

### ISSUE THREAD

**Issue by fahreddinozcan** [bounswe/bounswe2024group5#269]
### Issue Description

We need the meeting notes of LAB#2, 01.10.2024 to be added to wiki page.

### Tasks

- [x] Lab Meeting Notes#2

### Estimated Time

45

### Deadline

01/10/2024 - 18.00

### Reviewer

@semihYILMAZ37 - Deadline of the review (01/10/2024 -  20.00)

**Comment by fahreddinozcan** [comment]
@semihYILMAZ37 We've added the page [here](https://github.com/bounswe/bounswe2024group5/wiki/Lab-Meeting-%232-%7C-01.10.2024). For your review.

**Comment by fahreddinozcan** [comment]
After creating the issues for the action items, we need to update the meeting note. Please note.

**Comment by semihYILMAZ37** [comment]
Great work! Thanks for your effort.
