### ISSUE TITLE
Create a template for the lab reports

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#277]
## Description
We will submit a lab report every week. It is better to have a template for it.

## Estimated Time
25 mins.

## Deadline
Date(06/10/2024) - 23.00

## Reviewer
@semihYILMAZ37 - Deadline of the review(08/10/2024 - 15.00)

**Comment by ebrarkiziloglu** [comment]
I initiated the [lab report](https://github.com/bounswe/bounswe2024group5/wiki/Lab-Report-template).

**Comment by ebrarkiziloglu** [comment]
The issue is now ready for review @semihYILMAZ37.

**Comment by semihYILMAZ37** [comment]
the template looks cool. thanks for your effort!
