### ISSUE TITLE
Write Lab Meeting Notes #3

### ISSUE THREAD

**Issue by fahreddinozcan** [bounswe/bounswe2024group5#284]
### Issue Description

We need the meeting notes of LAB#3, 01810.2024 to be added to wiki page.

### Tasks

- [x] Lab Meeting Notes#3

### Estimated Time

45

### Deadline

08.10.2024 - 20.00

### Reviewer

@set120120

**Comment by fahreddinozcan** [comment]
@set120120 you can find the final state of the Lab Meeting #3 [here](https://github.com/bounswe/bounswe2024group5/wiki/Lab-Meeting-%233-%7C-08.10.2024). It's open for review.

**Comment by set120120** [comment]
I've added last related link to report. Now, everything has finished. Thank you for your effort @fahreddinozcan .
