### ISSUE TITLE
Create Initial Functionalities for Mobile

### ISSUE THREAD

**Issue by ramazanoacar** [bounswe/bounswe2024group5#287]
## Description
Add functionalities in the basic form for the 1st customer presentation. Tasks are listed below according to their priority decided on the meeting. Deadlines are not known for now.

## Tasks
- [x] #293
- [ ]  Create Quiz with real data
- [x]  Solving another user's quiz
- [x] #315
- [x] #295
- [x] #319

## Estimated Time
1 week

## Deadline
st Customer Presentation
Date(21/10/2024) - 17.59

## Reviewer
@HutkuC - Deadline of the review(21/10/2024 - 23.59)

**Comment by ebrarkiziloglu** [comment]
After our discussion with the front-end team, we decided to focus on the forum implementation for the Mobile, till the first customer presentation. 

So I think the pages can be ordered according to our priority as follows:
* p1 - Forum Page (with the navigation bar to switch between the quiz page and the forum page)
* p1 - ask a question in the forum page
* p2 - quiz page
* p2 - create a quiz page
* p3 - solve another user's quiz page 

I believe we will implement the p1 pages on time. We might have some time left to implement some of the p2 pages, we will see. Wdyt @ramazanoacar ?

**Comment by ramazanoacar** [comment]
@ebrarkiziloglu I agree. I believe we can finish both p1 but finish partially p1s.

**Comment by ebrarkiziloglu** [comment]
For the Customer Milestone 1, all of the functionalities, except for the Quiz Generation with real data, are implemented on the Mobile side. This issue is now ready for review.

**Comment by ramazanoacar** [comment]
@HutkuC can you review?

**Comment by set120120** [comment]
I am closing the issue. Thanks for your effort @ebrarkiziloglu @ramazanoacar @arincdemir and your review @HutkuC
