### ISSUE TITLE
Initialize the back-end for project

### ISSUE THREAD

**Issue by set120120** [bounswe/bounswe2024group5#288]
## Description
The initial version of back-end is need to be written. We need to prepare some important and basic functionalities for our project until Customer Presentation.

## Tasks
- [x] Dockerize the app.
- [x] #300

## Estimated Time
1 week

## Deadline
Customer Representation

## Reviewer
@HutkuC and @semihYILMAZ37 - Deadline of the review(dd/mm/yyyy - hour)

**Comment by HutkuC** [comment]
I think just one of us should be assigned to this issue. @set120120 Can you change the assignee, please?

**Comment by set120120** [comment]
I've edited the issue and I determined you as reviewer. @HutkuC

**Comment by set120120** [comment]
I've deleted the second task because it is not a part of initialization. So, I am waiting for your review. @HutkuC @semihYILMAZ37
