### ISSUE TITLE
Create Lab Meeting Notes #4

### ISSUE THREAD

**Issue by fahreddinozcan** [bounswe/bounswe2024group5#309]
## Description
We need to keep the meeting notes updated with the recent meeting.

## Tasks
- [x] Create Lab meeting notes#4 for the lab 

## Estimated Time
30m

## Deadline
15.10.2024 - 20.00

## Reviewer
@odenizddd

**Comment by fahreddinozcan** [comment]
@odenizddd I've created the meeting notes page [here](https://github.com/bounswe/bounswe2024group5/wiki/Lab-Meeting-%234-%7C-15.10.2024). Can you have a look

**Comment by odenizddd** [comment]
Very clean. Thank you.
