### ISSUE TITLE
Impelement Frontend Login Page

### ISSUE THREAD

**Issue by fahreddinozcan** [bounswe/bounswe2024group5#323]
## Description
We need to implement the authentication pages ui for the frontend application. Until the API is available, this will just be mock page. 

## Tasks
- [x] Sign-in Page
- [x] Sign-up Page

## Estimated Time
1h

## Deadline
20.10.2024 20.00

## Reviewer
@odenizddd

**Comment by fahreddinozcan** [comment]
@odenizddd the related PR is available for reviews #325

**Comment by odenizddd** [comment]
Everything look great. Thank you.
