### ISSUE TITLE
Individual Contribution Table [everyone writes for their own]

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#326]
## Description
We need to write our individual contributions to the [milestone report](https://github.com/bounswe/bounswe2024group5/wiki/451-Customer-Milestone-1-Report). 

* PS: Pay attention to the [instructions](https://moodle.bogazici.edu.tr/pluginfile.php/1721368/mod_resource/content/1/First%20Customer%20Presentation%20Deliverables.pdf). 

* Friendly reminder: Consider adding your weekly contributions to your personal wiki pages, as they're checked in the milestone gradings. 

## Tasks
- [x] ARINÇ DEMİR
- [x] ASUDE EBRAR KIZILOĞLU
- [x] FAHREDDİN ÖZCAN
- [x] HALİL UTKU ÇELİK
- [x] ÖZGÜR DENİZ DEMİR
- [x] RAMAZAN ONUR ACAR
- [x] SEMİH YILMAZ
- [x] SÜLEYMAN EMİR TAŞAN

## Estimated Time
30 mins

## Deadline
Date(25.10.2024) - 12.00

## Reviewer
No need

**Comment by odenizddd** [comment]
I think the following template for writing personal contributions might be beneficial. Feel free to copy and paste.

```
## Responsibilities
<!--- A general description of the responsibilities assigned to you. -->

## Main contributions
<!--- The overall description of your contributions to the project for Customer Milestone 1. -->

## Code-related significant issues
<!--- The issues that you have personally resolved or reviewed that contribute to the code base demonstrated during the demo. You must provide the relevant PRs and commits -->

## Non-code-related significant issues
<!--- The issues that you have personally resolved or reviewed. With brief explanations.-->

## Pull requests
<!--- Pull requests that you have created, merged, and reviewed. If you experienced any conflicts regarding the pull requests you have engaged in, briefly summarize the conflicts along with how they were resolved.-->

## Additional information
<!--- Mention any additional task you have performed that is not listed above. -->
```

**Comment by semihYILMAZ37** [comment]
Closing this since everybody completed their personal contribution at [the report](https://github.com/bounswe/bounswe2024group5/blob/main/reports/m1_group5.md).
