### ISSUE TITLE
Update labels

### ISSUE THREAD

**Issue by SouthAscend** [bounswe/bounswe2024group5#33]
## Description
Labels needs to be updated as we discussed in the class.

## Tasks
- [x] ~Add a label for learning~
- [x] ~Add a label for research~

## Deadline
25/02/2024 - 23.59

## Reviewer
@ramazanoacar  - 26/02/2024 23.59

**Comment by SouthAscend** [comment]
Labels are updated.

**Comment by ramazanoacar** [comment]
Reviewed successfully.
