### ISSUE TITLE
Implement Backend Quiz Endpoints

### ISSUE THREAD

**Issue by set120120** [bounswe/bounswe2024group5#340]
## Description
We need to implement quiz endpoints like POST, GET (to able to provide create quiz, solve quiz and delete a quiz)

## Tasks
- [x] Create quiz
- [x] Update quiz
- [x] Delete a quiz

## Estimated Time
6 hours

## Deadline
20.10.2024

## Reviewer
@ebrarkiziloglu

**Comment by set120120** [comment]
Everything is done.

**Comment by ebrarkiziloglu** [comment]
Everything works great and we are able to connect to backend from mobile. Thank you for your efforts!!
