### ISSUE TITLE
Create Backend Meeting Notes

### ISSUE THREAD

**Issue by set120120** [bounswe/bounswe2024group5#341]
## Description
The backend notes should be written.

## Tasks
- [x] Create and initialize the page.
- [x] Add 2 meeting notes.

## Estimated Time
30 mins
## Deadline
24.10.2024 - 23.59

## Reviewer
@fahreddinozcan - Deadline of the review(dd/mm/yyyy - hour)

**Comment by set120120** [comment]
Everything is done. You can check it [here](https://github.com/bounswe/bounswe2024group5/wiki/Back%E2%80%90End-Meeting-Notes-for-451) @fahreddinozcan

**Comment by fahreddinozcan** [comment]
The reports looks great, thanks for the good work on the backend.
