### ISSUE TITLE
Add a visual to Top Repo's Page - Güney

### ISSUE THREAD

**Issue by SouthAscend** [bounswe/bounswe2024group5#35]
## Description
Add an image to improve the visuality of the [Group's Top Repos](https://github.com/bounswe/bounswe2024group5/wiki/Group's-top-Repos).

## Tasks
- [x] ~Select and add an image in the [Godot](https://github.com/bounswe/bounswe2024group5/wiki/Group's-top-Repos#godot-engine)~

## Deadline
25/02/2024 - 23.59

## Reviewer
@odenizddd - 26/02/2024 23.59

**Comment by SouthAscend** [comment]
I've updated my part of the [Group's Top Repos](https://github.com/bounswe/bounswe2024group5/wiki/Group's-top-Repos) page with a visual.

**Comment by odenizddd** [comment]
Reviewed.
