### ISSUE TITLE
Increase similarity between mobile and web ui

### ISSUE THREAD

**Issue by ramazanoacar** [bounswe/bounswe2024group5#355]
## Description
Increase similarity between mobile and web ui, in lab 6.

## Tasks
- [x] Increase similarity in mobile
- [x] Increase similarity in web

## Estimated Time
60 minutes

## Deadline
Date(12/11/2024) - 18.00

## Reviewer
@semihYILMAZ37  - Deadline of the review(12/11/2024 - 20.00)

**Comment by semihYILMAZ37** [comment]
thanks for your efforts at [PR 352](https://github.com/bounswe/bounswe2024group5/pull/352). great work!
