### ISSUE TITLE
Create Profile Page

### ISSUE THREAD

**Issue by fahreddinozcan** [bounswe/bounswe2024group5#359]
## Description
We need to create a profile page for users, containing

- Username
- Profile Photo
- Email
- Quiz History
- Created Quizzes and Their Configurations
- Forum Posts
- Total Points from Quizzes

## Estimated Time
4h

## Deadline
20.11.2024

## Reviewer
@odenizddd

**Comment by fahreddinozcan** [comment]
This is addressed on #392.

**Comment by odenizddd** [comment]
I tlook very cool.
