### ISSUE TITLE
Create Profile Page - Mobile

### ISSUE THREAD

**Issue by ramazanoacar** [bounswe/bounswe2024group5#360]
## Description
Create Profile page and settings accordingly.

## Tasks
- [x] #361
- [x] Finalize pages for the milestore

## Estimated Time
360 minutes

## Deadline
Date(21/11/2024) - 23.59

## Reviewer
@ebrarkiziloglu  - Deadline of the review(22/11/2024 - 23.59)

**Comment by ramazanoacar** [comment]
hello @ebrarkiziloglu , I forgot to change the status of this issue. Can you review now, please?

**Comment by ebrarkiziloglu** [comment]
I reviewed the PR #426. Great work! Closing the issue.
