### ISSUE TITLE
Create the first draft of a Project

### ISSUE THREAD

**Issue by SouthAscend** [bounswe/bounswe2024group5#37]
## Description
We're encouraged to use projects, this is a project for the first assignment.

## Tasks
- [x] ~Research & learn about the "Projects" Feature~
- [x] ~Create the project~

## Deadline
25/02/2024 - 23.59

## Reviewer
@Ultiminati  - 26/02/2024 23.59

**Comment by SouthAscend** [comment]
I've created the [Project](https://github.com/orgs/bounswe/projects/37) and filled all the parts related to my past issues.

**Comment by Ultiminati** [comment]
The draft is done and the project template is functioning.
