### ISSUE TITLE
Create Software Quality Plan

### ISSUE THREAD

**Issue by fahreddinozcan** [bounswe/bounswe2024group5#378]
## Description
In order to keep track of the softwre quality, we need to create a plan of the things to be done until the next milestone. This content includes

## Tasks
- [X] Test Coverage
- [X] Test Scope
- [X] Common Content
- [X] Manuel Priority Feature Testing

## Estimated Time
1h

## Deadline
19.11.2024

## Reviewer
@semihYILMAZ37

**Comment by fahreddinozcan** [comment]
@semihYILMAZ37 I've created the software quality plan. Please see [related wiki page](https://github.com/bounswe/bounswe2024group5/wiki/Software-Quality-Plan).

**Comment by semihYILMAZ37** [comment]
Thanks for your effort! This comprehensive plan will ensure the quality of our product.
