### ISSUE TITLE
Implement Image Upload Feature

### ISSUE THREAD

**Issue by fahreddinozcan** [bounswe/bounswe2024group5#402]
## Description
We need to allow users to add images as quiz metadata and profile photos. Thanks to the changes introduced in #388, it's now possible

## Tasks
- [x] Allow Quiz Image Metadata Upload
- [x] Allow Profile Photo Upload

## Estimated Time
4h

## Deadline
25.11.2024

## Reviewer
@odenizddd

**Comment by fahreddinozcan** [comment]
This is addressed with #403  and #431.

**Comment by odenizddd** [comment]
LGTM.
