### ISSUE TITLE
Discuss changing the format of meeting notes

### ISSUE THREAD

**Issue by Ultiminati** [bounswe/bounswe2024group5#41]
## Description
In the PS, "outcomes" sections have been said to be too general, and we should split the results of the meeting as discussions, and actions. Actions are things that, about them, there can be an issue opened.

## Tasks
- [ ] Discuss it!

## Deadline
Date(26/02/2024) - 23.00

## Reviewer
@arincdemir

**Comment by arincdemir** [comment]
I can see the discussion in the meeting notes.
