### ISSUE TITLE
Update the issue template - Estimated Time

### ISSUE THREAD

**Issue by SouthAscend** [bounswe/bounswe2024group5#42]
## Description
The issue template is required to have an estimated time field.

## Tasks
- [X] ~Add an estimated time field.~

## Deadline
26/02/2024 - 23.59

## Reviewer
@ebrarkiziloglu  - 27/02/2024 17.00

**Comment by SouthAscend** [comment]
I've added an Estimated Time field. I've corrected the comments; in the previous version, comments were visible in the preview. This shouldn't be the case now. I've updated the about part and added the "status: new" label as a default.

**Comment by ebrarkiziloglu** [comment]
Great work! Thank you Güney. Closing this issue now.
