### ISSUE TITLE
Add Mobile API calls for Forum Page, post details, comments and upvotes

### ISSUE THREAD

**Issue by ramazanoacar** [bounswe/bounswe2024group5#423]
## Description
Add Mobile API calls for Forum Page, post details, comments and upvotes

## Tasks
- [x] Finalize Forum Page functionality's with api calls 
- [x] Finalize Post Details screen including comments and upvotes

## Estimated Time
240 minutes

## Deadline
Date(25/11/2024) - 15.00

## Reviewer
@ebrarkiziloglu  - Deadline of the review(25/11/2024 - 18.00)

**Comment by ramazanoacar** [comment]
hello @ebrarkiziloglu , I forgot to change the status of this issue. Can you review now, please?

**Comment by ebrarkiziloglu** [comment]
I reviewed the PR #426. Closing the issue now. Great work!
