### ISSUE TITLE
Create a Issue Form Template

### ISSUE THREAD

**Issue by SouthAscend** [bounswe/bounswe2024group5#45]
## Description
A new issue template needs to be created for ease of use in future issues.

## Tasks
- [ ] Learn yaml
- [ ] Create the new configuration file
- [ ] Test it

## Estimated Time
45 min

## Deadline
03/03/2024 - 23.59

## Reviewer
@semihYILMAZ37 - 04/03/2024 23.59

**Comment by SouthAscend** [comment]
I've created and added the issue template as issue form. There should be a prompt in the new issue screen. [The template](https://github.com/bounswe/bounswe2024group5/blob/main/.github/ISSUE_TEMPLATE/issue_template_form.yml).

@semihYILMAZ37 issue is in need of a review.

**Comment by semihYILMAZ37** [comment]
new template looks cool thanks for it
