### ISSUE TITLE
Update Favorite Repo

### ISSUE THREAD

**Issue by set120120** [bounswe/bounswe2024group5#46]
## Description
Previous design and texts need to be updated.

## Tasks
- [x] Review and edit text
- [x] Add a proper photograph

## Estimated Time
15 minutes

## Deadline
27.02.2024 - 23.59

## Reviewer
@arincdemir

**Comment by set120120** [comment]
I've updated my personal wiki page. I've added new texts and a photograph.

**Comment by arincdemir** [comment]
I see that you updated your part for Guava.
