### ISSUE TITLE
[MILESTONE 2] Individual Contribution Table [everyone writes for their own]

### ISSUE THREAD

**Issue by fahreddinozcan** [bounswe/bounswe2024group5#460]
## Description
We need to write our individual contributions to the [milestone report](https://github.com/bounswe/bounswe2024group5/wiki/451-Customer-Milestone-2-Report). 

* PS: Pay attention to the [instructions](https://moodle.bogazici.edu.tr/pluginfile.php/1734206/mod_resource/content/3/Second%20Customer%20Presentation%20Deliverables.pdf). 

* Friendly reminder: Consider adding your weekly contributions to your personal wiki pages, as they're checked in the milestone gradings. 

## Tasks
- [x] ARINÇ DEMİR
- [x] ASUDE EBRAR KIZILOĞLU
- [x] FAHREDDİN ÖZCAN
- [x] HALİL UTKU ÇELİK
- [x] ÖZGÜR DENİZ DEMİR
- [x] RAMAZAN ONUR ACAR
- [x] SEMİH YILMAZ
- [x] SÜLEYMAN EMİR TAŞAN

## Estimated Time
30 mins

## Deadline
Date(25.10.2024) - 12.00

## Reviewer
No need

**Comment by ebrarkiziloglu** [comment]
it took me 1.5 hours to complete my individual contribution section 😄

**Comment by ebrarkiziloglu** [comment]
Great job team! 🤩
