### ISSUE TITLE
Update RAM

### ISSUE THREAD

**Issue by semihYILMAZ37** [bounswe/bounswe2024group5#461]
## Description
Responsibility Assignment Matrix should be updated according to new issues and PRs.

## Estimated Time
2 hours

## Deadline
Date(29/11/2024) - 20:00

## Reviewer
@ebrarkiziloglu  - Deadline Date(29/11/2024) - 22:00

**Comment by semihYILMAZ37** [comment]
@ebrarkiziloglu this is ready for review now

**Comment by ebrarkiziloglu** [comment]
LGTM! thanks for your efforts
