### ISSUE TITLE
Update the Meeting notes of the first meeting

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#47]
## Description
The meeting notes of the first meeting needs some updates according to the new template. 

## Estimated Time
15 mins. 

## Deadline
Date(26/02/2024) - 23.00

## Reviewer
@ramazanoacar  - Deadline of the review(27/02/2024 - 09.00)

**Comment by ramazanoacar** [comment]
First meeting notes seem properly updated in accordance to new template.

**Comment by ramazanoacar** [comment]
First meeting notes seem properly updated in accordance to new template.
