### ISSUE TITLE
Add Leaderboard page for mobile

### ISSUE THREAD

**Issue by ramazanoacar** [bounswe/bounswe2024group5#474]
## Description
Leaderboard page should be added and configurations and updates should be made in the existing components

## Tasks
- [x] Add leaderboard with dummy data and update existing components with respect to it
- [x] connect the page with the backend

## Estimated Time
60 minutes

## Deadline
Date(16/12/2024) - 12.00

## Reviewer
@fahreddinozcan  - Deadline of the review(17/12/2024 - 12.00)

**Comment by ramazanoacar** [comment]
hello @fahreddinozcan, can you review the issue, please?

**Comment by ramazanoacar** [comment]
These are the related PR's:

https://github.com/bounswe/bounswe2024group5/pull/472

https://github.com/bounswe/bounswe2024group5/pull/525

**Comment by fahreddinozcan** [comment]
Thanks for the quality work, this feature is well implemented. Closing this
