### ISSUE TITLE
Add quiz solving status to mobile

### ISSUE THREAD

**Issue by ramazanoacar** [bounswe/bounswe2024group5#476]
## Description
Quiz solving status (completed, in progress etc.) should be showed on home page and profile page

## Tasks
- [x] Add quiz status to home page
- [x] Add quiz status to profile page

## Estimated Time
90 minutes

## Deadline
Date(16/12/2024) - 12.00

## Reviewer
@HutkuC  - Deadline of the review(17/12/2024 - 12.00)

**Comment by ramazanoacar** [comment]
https://github.com/bounswe/bounswe2024group5/pull/507

Hello @HutkuC , the related PR is above. Can you review the issue please?

**Comment by HutkuC** [comment]
lgtm
