### ISSUE TITLE
Add related posts for the the quiz solving screen on Mobile

### ISSUE THREAD

**Issue by ramazanoacar** [bounswe/bounswe2024group5#477]
## Description
Related posts for the word of the question should be added to the mobile

## Tasks
- [x]  add related post functionality and api calls

## Estimated Time
60 minutes

## Deadline
Date(16/12/2024) - 12.00

## Reviewer
@odenizddd  - Deadline of the review(16/12/2024 - 12.00)

**Comment by ramazanoacar** [comment]
hello @odenizddd , below is the PR including this issue's solution. Can you review please?

https://github.com/bounswe/bounswe2024group5/pull/472

**Comment by odenizddd** [comment]
@ramazanoacar  I think might be better if someone from the mobile team reviews it, because I'm not very familiar with React Native. Is there any specific reason you wanted me to review this issue?

**Comment by ramazanoacar** [comment]
no spesific reason, I tried to add different reviewers for each issue. I am closing the issue.
