### ISSUE TITLE
Add quiz suggestions after quiz finishes

### ISSUE THREAD

**Issue by ramazanoacar** [bounswe/bounswe2024group5#478]
## Description
add quiz suggestions after a user finishes the quiz. Suggest prioritizing the elo of the user and quiz.

## Tasks
- [x] add the component for quiz suggestion
- [x] handle the logic for proper quiz suggestion

## Estimated Time
90 minutes

## Deadline
Date(16/12/2024) - 12.00

## Reviewer
@semihYILMAZ37  - Deadline of the review(17/12/2024 - 12.00)

**Comment by ramazanoacar** [comment]
https://github.com/bounswe/bounswe2024group5/pull/525

Hello @semihYILMAZ37 , related PR is above. Can you review this issue, please?

**Comment by semihYILMAZ37** [comment]
From my own experience, quiz suggestion works well on the mobile app. Cool job!
