### ISSUE TITLE
Add image to your favorite GitHub repo - Ebrar Kiziloglu

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#49]
## Description
Add an image of LLaMA to your favorite repository section in Wiki. 

## Estimated Time
10 mins

## Deadline
Date(26/02/2024) - 22.00

## Reviewer
@semihYILMAZ37 - Deadline of the review(27/02/2024 - 09.00)

**Comment by ebrarkiziloglu** [comment]
I added an image of LLAMA to [our favorite repos page](https://github.com/bounswe/bounswe2024group5/wiki/Group's-top-Repos).

**Comment by semihYILMAZ37** [comment]
the job is done correctly by Ebrar. the issue is now completed.
