### ISSUE TITLE
Fix Profile Page Routing

### ISSUE THREAD

**Issue by fahreddinozcan** [bounswe/bounswe2024group5#493]
## Description
Right now, it's not possible to view other user's profiles due to a bug, causing the client to always fetch the own profile of the user. We should fix that.

## Estimated Time
30m

## Deadline
14.12.2024

## Reviewer
@fahreddinozcan

**Comment by odenizddd** [comment]
Fixed [here](https://github.com/bounswe/bounswe2024group5/pull/513).

**Comment by odenizddd** [comment]
Reviewed and approved by @ebrarkiziloglu
