### ISSUE TITLE
Implement Quiz and Question Favourite feature

### ISSUE THREAD

**Issue by fahreddinozcan** [bounswe/bounswe2024group5#494]
## Description
The issue description.

## Tasks
- [x] Favourite Quiz
- [x] Favourite Question

## Estimated Time
2h

## Deadline
17.12.2024

**Comment by odenizddd** [comment]
Hi @fahreddinozcan .

I made some progress in this issue. Right now users can favorite and unfavorite quizzes and question. But there are some other things that we might want to implement.

1. Being able to see which quizzes and questions are favorited in the profile page.
2. Being able to favorite a quiz in the quiz solving page.

They are not super high priority, but I'm writing them here in case we have more time than we anticipated for MS3 and find ourselves thinking what else should we be working on.

We can close this issue after you review my pull request regarding this issue and open new issues to implement the features I listed above if we decide to implement them later.

**Comment by odenizddd** [comment]
Reviewed and approved by @fahreddinozcan
