### ISSUE TITLE
[Frontend] Quiz Link Copy and Share Feature

### ISSUE THREAD

**Issue by fahreddinozcan** [bounswe/bounswe2024group5#499]
## Description
We should add a reference link on the quiz listing page to copy and share the quiz links

## Tasks
- [x] Copy link

## Estimated Time
1h

## Deadline
17.12.2024

## Reviewer
@Reviewer - Deadline of the review(dd/mm/yyyy - hour)

**Comment by odenizddd** [comment]
Resolved [here](https://github.com/bounswe/bounswe2024group5/pull/516).
