### ISSUE TITLE
[Frontend] Add Warning for Already Completed Quiz

### ISSUE THREAD

**Issue by fahreddinozcan** [bounswe/bounswe2024group5#517]
## Description
When a user tries to solve a quiz the second time, it's not possible to gain points from that quiz. When a user clicks on the quiz, we need to inform them about this situtation.

## Tasks
- [x] Add information Modal regarding already completed quiz

## Estimated Time
1h

## Deadline
Date(dd/mm/yyyy) - Hour

## Reviewer
@Reviewer - Deadline of the review(dd/mm/yyyy - hour)

**Comment by odenizddd** [comment]
Resolved by @fahreddinozcan [here](https://github.com/bounswe/bounswe2024group5/pull/518).
