### ISSUE TITLE
[Frontend] Retrieve Question Hint Based On Question Type

### ISSUE THREAD

**Issue by fahreddinozcan** [bounswe/bounswe2024group5#522]
## Description
Right now, when fetching the question hint, independent of the question type, we use the question's word as the tooltip and fetch the word. This creates confusion for words that exist in both languages like Erik

## Tasks
- [  ] Consider question type for fetching hint

## Estimated Time
30m

## Deadline
17.12.2024

## Reviewer
@odenizddd

**Comment by odenizddd** [comment]
Resolved by @fahreddinozcan [here](https://github.com/bounswe/bounswe2024group5/pull/523).
