### ISSUE TITLE
Add your weekly contribution - Ebrar Kiziloglu

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#54]
## Tasks
- [x] Add your weekly contributions to the personal wiki page.

## Estimated Time
15 mins.

## Deadline
Date(26/02/2024) - 23.30

## Reviewer
@set120120 - Deadline of the review(27/02/2024 - 09.00)

**Comment by ebrarkiziloglu** [comment]
I added my contributions under the title [Week 2](https://github.com/bounswe/bounswe2024group5/wiki/Asude-Ebrar-K%C4%B1z%C4%B1lo%C4%9Flu#contributions) in my personal page.

**Comment by set120120** [comment]
I checked your personal page and everythings is completed.

**Comment by set120120** [comment]
I checked your personal page and everythings is completed.
