### ISSUE TITLE
Update the README file of the repo

### ISSUE THREAD

**Issue by Ultiminati** [bounswe/bounswe2024group5#56]
## Description
To link to the wiki and the other relevant places, README should be updated as discussed in the meeting.

## Tasks
- [x] Structure the file
- [x] Add wiki and the other links
- [x] Final touches

## Estimated Time
60

## Deadline
Date(07/03/2024) - 18.00

## Reviewer
@ebrarkiziloglu  - Deadline of the review(11/03/2024 - 18.00)

**Comment by SouthAscend** [comment]
I'm only responsible for the banner design of this issue.
![Project TBA](https://github.com/bounswe/bounswe2024group5/assets/137878803/6fe8199b-9976-4d58-b125-7d0b19000303)

**Comment by Ultiminati** [comment]
@ebrarkiziloglu I've updated the review date. Finally, it is worthy of a review.

**Comment by ebrarkiziloglu** [comment]
Great add @Ultiminati. Closing the issue now.
