### ISSUE TITLE
Do research on Web Application Development and Take Notes

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#60]
## Description
The professors [recommends](https://moodle.bogazici.edu.tr/mod/forum/discuss.php?d=146623) us to make a domain analysis on the Web application development.

## Tasks
- [x] #68
- [x] Take some summary notes.
- [x] #69

## Estimated Time
60 mins.

## Deadline
Date(05/03/2024) - 10.00

## Reviewer
@Ultiminati - Deadline of the review(06/03/2024 - 10.00)

**Comment by SouthAscend** [comment]
@set120120 wrote the main part of the page, and I've added the example part. [The page](https://github.com/bounswe/bounswe2024group5/wiki/Web-Application-Development) is online now.

@Ultiminati The issue is in need of a review.

**Comment by Ultiminati** [comment]
The research is well documented and well informed.
