### ISSUE TITLE
4.1 User Manual (manual will be written) - @ebrarkiziloglu

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#614]
We need a detailed User Manual to be added to the final report. 

## Estimated Time
40 mins.

## Deadline
Date(20/12/2024) - 18.00

## Reviewer
@semihYILMAZ37 - Deadline of the review(20/12/2024- 22.00)

**Comment by semihYILMAZ37** [comment]
The manual is very helpful for new users. Thanks for it!
