### ISSUE TITLE
4.2 System Manual (manual will be written) - @ebrarkiziloglu

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#615]
We need a detailed System Manual to be added to the final report. 

## Estimated Time
40 mins.

## Deadline
Date(20/12/2024) - 18.00

## Reviewer
@HutkuC - Deadline of the review(20/12/2024- 22.00)

**Comment by ebrarkiziloglu** [comment]
I have written the [manual](https://github.com/bounswe/bounswe2024group5/wiki/System-Manual), issue is ready for review.

**Comment by HutkuC** [comment]
lgtm
