### ISSUE TITLE
2.4 UI - UX - @ebrarkiziloglu

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#616]
We need to display the web and mobil interfaces, to include in the final report.

## Estimated Time
80 mins.

## Deadline
Date(20/12/2024) - 18.00

## Reviewer
@fahreddinozcan - Deadline of the review(20/12/2024- 22.00)

**Comment by ebrarkiziloglu** [comment]
I collected all of the mobile and web interface screenshots in a [wiki page](https://github.com/bounswe/bounswe2024group5/wiki/UI-Interfaces).

**Comment by fahreddinozcan** [comment]
Thanks for the high quality work, LGTM
