### ISSUE TITLE
Do research on developing a semantic browse and search application and Take Notes

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#62]
## Description
The professors [recommends](https://moodle.bogazici.edu.tr/mod/forum/discuss.php?d=146623) us to get familiar with how to develop a semantic browse and search application.

## Tasks
- [x] #66
- [x] Take some summary notes.
- [x] Provide resources for your teammates on this topic. 

## Estimated Time
60 mins.

## Deadline
Date(06/03/2024) - 10.00

## Reviewer
@semihYILMAZ37  - Deadline of the review(07/03/2024 - 10.00)

**Comment by ebrarkiziloglu** [comment]
Did research on semantic search and prepared the corresponding [wikipage](https://github.com/bounswe/bounswe2024group5/wiki/Semantic-Information-Browse-and-Search-Application).

**Comment by semihYILMAZ37** [comment]
thanks for the research. it looks cool.
