### ISSUE TITLE
Update RAM

### ISSUE THREAD

**Issue by set120120** [bounswe/bounswe2024group5#620]
## Description
The RAM should be updated according to new issues from MS2 to MS3

## Tasks
- [x] Update RAM

## Estimated Time
25 mins

## Deadline
20.12.2024 - 19.59

## Reviewer
@semihYILMAZ37

**Comment by set120120** [comment]
Everything is ready. Could you please check it?

**Comment by semihYILMAZ37** [comment]
RAM looks well. thanks for your efforts!
