### ISSUE TITLE
Create Meeting Notes #3

### ISSUE THREAD

**Issue by set120120** [bounswe/bounswe2024group5#64]
## Description
Create [Meeting Notes #3](https://github.com/bounswe/bounswe2024group5/wiki/Meeting-Notes-%233) from notes I take during meeting.

## Tasks
- [x] Create meeting notes for this week

## Estimated Time
25 mins
## Deadline
03.03.2024 - 23.59

## Reviewer
@ebrarkiziloglu

**Comment by set120120** [comment]
I created meeting notes according to template on wiki.

**Comment by ebrarkiziloglu** [comment]
Meeting notes were created accordingly. Thanks Süleyman.
