### ISSUE TITLE
Think about a Domain name for the browser. 

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#70]
## Description
Every team member will think about at least one domain idea for our semantic information browser. 
Also we should provide a reason why we think this is a good domain for the project.

## Estimated Time
60 mins per assignee.

## Deadline
Date(09/03/2024) - 23.59

## Reviewer
No reviewer is needed this time.

**Comment by ebrarkiziloglu** [comment]
We discussed our ideas [here](https://github.com/bounswe/bounswe2024group5/discussions/71). 
Now we will [vote](https://github.com/bounswe/bounswe2024group5/discussions/78) on these options and chose the most favorable domain. 
Closing this issue now.

**Comment by Ultiminati** [comment]
> We discussed our ideas [here](https://github.com/bounswe/bounswe2024group5/discussions/71). 
> Now we will [vote](https://directpoll.com/v?XDVhEtzwPlEfT8DrEZcgsKzvapKlEnSGrJk) on these options and chose the most favorable domain. 
> Closing this issue now.

We can consider polls from Github Discussions maybe?

**Comment by SouthAscend** [comment]
> We can consider polls from Github Discussions maybe?

GitHub Discussions' polls does not have enough options.
