### ISSUE TITLE
Determine Requirements for the 'Non-functional' category.

### ISSUE THREAD

**Issue by arincdemir** [bounswe/bounswe2024group5#74]
### Issue Description

In the planning phase of the project, we are expected to determine the requirements specification.

### Tasks

- [x] Determine non-functional requirements.
- [x] Write them in the requirements page.

### Estimated Time

70

### Deadline

09/03/2024 - 23.59

### Reviewer

@ramazanoacar - 10/03/2024 - 23.59

**Comment by arincdemir** [comment]
I added the requirements to the wiki page. @ramazanoacar Take a look.

**Comment by ramazanoacar** [comment]
@arincdemir the non functional requirements seems inclusive. Thanks for your effort! I am not sure whether we should divide them into subcategories, but i am now closing the issue. If you want, you may divide them into subcategories I believe.

**Comment by arincdemir** [comment]
I will work on that.
