### ISSUE TITLE
Determine the requirements for the feed page

### ISSUE THREAD

**Issue by SouthAscend** [bounswe/bounswe2024group5#76]
## Description
The requirements page should have a part about feed.

## Tasks
- [x] Research about what the requirements of the feed page should be.
- [x] Add the requirements to the related page.

## Estimated Time
60 min

## Deadline
10/03/2024 - 23.59

## Reviewer
@semihYILMAZ37  - 11/03/2024 23.59

**Comment by SouthAscend** [comment]
I've added the part to the [requirements](https://github.com/bounswe/bounswe2024group5/wiki/Requirements) page. The issue is in need of a review. @semihYILMAZ37

**Comment by semihYILMAZ37** [comment]
the requirements of the feed page looks good. thanks for it.
