### ISSUE TITLE
Specify user-to-user interaction requirements.

### ISSUE THREAD

**Issue by odenizddd** [bounswe/bounswe2024group5#81]
## Description
Research the requirements of the previous CmpE 352 projects to get an idea of what user-to-user interaction requirements might look like and enlist our project's requirements to requirements page in the wiki.

## Estimated Time
30 minutes.

## Reviewer
@ebrarkiziloglu

**Comment by ebrarkiziloglu** [comment]
Hey @odenizddd! As the reviewer of the issue, I wanted to check the status of this issue. Is it getting done?

**Comment by odenizddd** [comment]
Yes @ebrarkiziloglu. I added the requirements.

**Comment by ebrarkiziloglu** [comment]
Great! I was confused because of the labels of the issue. 
Updating the issue labels and closing the issue now.

**Comment by ebrarkiziloglu** [comment]
@odenizddd Please add start and end dates to the issue for the project plan view.
