### ISSUE TITLE
Gather the questions about the requirements we gathered in the Discussions

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#82]
## Description
We collected our question in a [thread](https://github.com/bounswe/bounswe2024group5/discussions/72) in the Discussions section of our repo.
They need to be organized under a wiki page.

## Estimated Time
15 mins.

## Deadline
Date(14/03/2024) - 17.00

## Reviewer
@SouthAscend - Deadline of the review(14/03/2024 - 23.59)

**Comment by ebrarkiziloglu** [comment]
I created the [wikipage](https://github.com/bounswe/bounswe2024group5/wiki/Questions-About-Requirements) adding all question we had so far. 

I will continue to add the future questions we might have in the following couple of days.

**Comment by ebrarkiziloglu** [comment]
As of today, we collected all our questions and held a [customer meeting](https://github.com/bounswe/bounswe2024group5/wiki/Customer-Meeting-%231) with TA to ask our questions. 
This issue needs review now @SouthAscend.

**Comment by SouthAscend** [comment]
We've discussed the questions in the meeting. Having all the questions organized on a single page was helpful.
