### ISSUE TITLE
Create project and first milestone

### ISSUE THREAD

**Issue by ramazanoacar** [bounswe/bounswe2024group5#83]
### Issue Description

Create the new project and first milestone

### Tasks

- [x] Create Project
- [x] Create First Milestone

### Estimated Time

30

### Deadline

15/03/2024 - 23:59

### Reviewer

@set120120 - Deadline of the Review (17/03/2024 23:59)

**Comment by ramazanoacar** [comment]
@set120120 could you please check if i understand the action item correct? Because It took less time then I estimated. Also, @odenizddd your further review could be meaningful because I couldn't attend the last meeting and you were the moderator I guess for that meeting.

**Comment by odenizddd** [comment]
@ramazanoacar I haven't got any experience in project creation and milestones on this platform so I can't review your work with confidence. Perhaps we should ask another teammate to review the task.

**Comment by ramazanoacar** [comment]
@ebrarkiziloglu is it possible that you have any experience in project creation and milestones? If so, your assistance in reviewing this task for the milestone and project creation could be very helpful.

**Comment by ebrarkiziloglu** [comment]
@ramazanoacar the Project view LGTM. This will be the Project we will use until the end of our project, as we discussed previously. So this Project is not only for the first milestone, you can consider changing the name of the Project.
About the first milestone you [created](https://github.com/bounswe/bounswe2024group5/milestone/1), you can consider adding the deadline, March 17th. After that, this milestone is supposed to be shown in the 'Roadmap' view of the Project you initiated. 
I hope this insight helps.

**Comment by ebrarkiziloglu** [comment]
In terms of the content of the first milestone: here, I quote the description provided by the teaching-staff:

"You will have a milestone on 17th of March where your **repo**, **research**, **plan**, and **requirements** will be submitted. 
Your repo, where you have been documenting your work, is also a deliverable. We will be examining  your contributions as well as the management related artifacts.
Outcome: Elicitation related **questions**, requirements specification, **scenarios**, and **mockups**."

You can alter the milestone name and description according to this info.

**Comment by ramazanoacar** [comment]
@ebrarkiziloglu your insight was a great assistance. I changed the name of the project and also simplified and corrected the description and due date of the first milestone

**Comment by ebrarkiziloglu** [comment]
Thank you @ramazanoacar I'm glad it helped. I am not sure why the milestone is still not visible in the under the Roadmap in our Project though.

**Comment by ramazanoacar** [comment]
@ebrarkiziloglu I found now how to do it. I think I was supposed add it from the markers part. It should be visible now.

**Comment by set120120** [comment]
I read everything written and I would like to thank @ebrarkiziloglu for her advices. @ramazanoacar everything seems fine. Project and milestone can be used for their intended purpose. Thanks for your effort.
