### ISSUE TITLE
Update the project with past issues - Güney

### ISSUE THREAD

**Issue by SouthAscend** [bounswe/bounswe2024group5#86]
## Description
Our project needs to be updated with everyone's past issues. And necessary fields like start and end dates.

## Tasks
- [ ] Add all the past issues to the project.
- [ ] Update the necessary fields.

## Estimated Time
45 min

## Deadline
17/03/2024 - 23.59

## Reviewer
@ramazanoacar  - 18/03/2024 17.00

**Comment by SouthAscend** [comment]
Every issue that's been assigned to me (except for the ones that were assigned to everybody) should be in the project with the correct values in the corresponding fields now. The issue is in need of a review @ramazanoacar.

**Comment by ramazanoacar** [comment]
@SouthAscend saw your comment now. They seem fine. Great Job
