### ISSUE TITLE
Add Glossary to the Requirements page.

### ISSUE THREAD

**Issue by SouthAscend** [bounswe/bounswe2024group5#87]
## Description
A glossary section needs to be added to the [Requirements Page](https://github.com/bounswe/bounswe2024group5/wiki/Requirements).

## Tasks
- [x] Add the glossary section.

## Estimated Time
20 min

## Deadline
17/03/2024 - 23.59

## Reviewer
@HutkuC - 18/03/2024 17.00

**Comment by SouthAscend** [comment]
I've added the [glossary](https://github.com/bounswe/bounswe2024group5/wiki/Requirements#glossary) part to the [Requirements Page](https://github.com/bounswe/bounswe2024group5/wiki/Requirements). @HutkuC The issue is in need of a review.

**Comment by ebrarkiziloglu** [comment]
Hey @HutkuC, let's close issues related to the previous milestone!
