### ISSUE TITLE
Update the Requirements for Posting

### ISSUE THREAD

**Issue by ebrarkiziloglu** [bounswe/bounswe2024group5#90]
## Description
After having the first customer meeting and deciding on our domain, the requirements need some adjustments. 

## Tasks
- [x] Reflect the answers to our questions from the customer regarding posting. 
- [x] Reflect the music domain.

## Estimated Time
20 mins.

## Deadline
Date(16/03/2024) - 22.00

## Reviewer
@arincdemir  - Deadline of the review(17/03/2024 - 23.59)

**Comment by ebrarkiziloglu** [comment]
I have updated the posting requirements. This issue is now in need of review @arincdemir.

**Comment by arincdemir** [comment]
@ebrarkiziloglu If I remember correctly, the teacher suggested us to use "shall" most of the time. I think you can change the format "the user can ..." into "the user shall be able to ...".

**Comment by ebrarkiziloglu** [comment]
Thank you for the info @arincdemir, I must have missed that suggestion. Fixed it now.

**Comment by arincdemir** [comment]
Looks good, thanks!
