### ISSUE TITLE
Update Search Requirements

### ISSUE THREAD

**Issue by set120120** [bounswe/bounswe2024group5#93]
## Description
The domain idea has been changed. Therefore, search requirements also need to be changed.

## Tasks
- [x] Review previous requirements.
- [x] Add new requirements.

## Estimated Time
40 mins

## Deadline
Date(16.03.2024) - 23.59

## Reviewer
@odenizddd

**Comment by set120120** [comment]
I updated the search requirements according to the new domain. I deleted the ones related to the previous domain and added new requirements. You can review it now. @odenizddd

**Comment by odenizddd** [comment]
Good work. Thank you @set120120
