### ISSUE TITLE
Construct communication plan table

### ISSUE THREAD

**Issue by set120120** [bounswe/bounswe2024group5#95]
## Description
We need to represent our [communication plan](https://github.com/bounswe/bounswe2024group5/wiki/Communication-Plan) in a much more better way, so we decided to construct a table to do that.

## Tasks
- [x] Construct the table according to team's communication plan.

## Estimated Time
15 mins

## Deadline
16.03.2024 - 23.59

## Reviewer
@ebrarkiziloglu

**Comment by set120120** [comment]
I've construct the table. Could you please check them? @ebrarkiziloglu

**Comment by ebrarkiziloglu** [comment]
LGTM! 💯
