### ISSUE TITLE
Do some visual arrangement to RAM

### ISSUE THREAD

**Issue by set120120** [bounswe/bounswe2024group5#96]
## Description
There should be some visual differences like colorful squares to differentiate roles in a responsibility. Therefore, I decided to add specific color to the specific roles.

C-Contributor 🟩
R-Reviewer 🟦
M-Moderator 🟥
A-Attendee 🟧
L-Lead 🟨
N-No square

## Tasks
- [x] Decide which color to which role.
- [x] Change all columns and rows

## Estimated Time
15 mins

## Deadline
16.03.2024

## Reviewer
@ebrarkiziloglu

**Comment by set120120** [comment]
I've added appropriate squares to all cells. It needs to your review. @ebrarkiziloglu

**Comment by ebrarkiziloglu** [comment]
RAM looks easier to comprehend now @set120120, thank you!
Closing the issue now.
