### ISSUE TITLE
Add weekly contributions

### ISSUE THREAD

**Issue by set120120** [bounswe/bounswe2024group5#97]
## Description
I need to add weekly contributions before milestone.

## Tasks
- [x] Add week 6 to [my personal page](https://github.com/bounswe/bounswe2024group5/wiki/S%C3%BCleyman-Emir-Ta%C5%9Fan)

## Estimated Time
10 mins 

## Deadline
16.03.2024 - 23.59

## Reviewer
@Ultiminati

**Comment by set120120** [comment]
I've added all things that I've done in this week. @Ultiminati It is open for your review.

**Comment by Ultiminati** [comment]
Greatly done!
