### ISSUE TITLE
Create wiki page for mockups

### ISSUE THREAD

**Issue by Ultiminati** [bounswe/bounswe2024group5#99]
### Issue Description

Create the wiki page for mockups and add link to the general wiki.

### Tasks

- [x] Just do it!

### Estimated Time

25

### Deadline

18.03.2024 - 00.30

### Reviewer

@ebrarkiziloglu  - Deadline of the review (18/03/2024 - 15.00)

**Comment by Ultiminati** [comment]
Added it in [here](https://github.com/bounswe/bounswe2024group5/wiki/Mockups-for-the-project.).
You can close the issue @ebrarkiziloglu.

**Comment by ebrarkiziloglu** [comment]
LGTM!
